# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class B9s < Formula
  desc "Fast, focused TUI viewer and editor for beads projects"
  homepage "https://github.com/vanderheijden86/b9s"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vanderheijden86/b9s/releases/download/v1.3.0/b9s_1.3.0_darwin_amd64.tar.gz"
      sha256 "7aaa3f195b939f5d0d30a8e8d1ca8b297fe80e2adb3fe0436b84ddc07d2b4c76"

      define_method(:install) do
        bin.install "b9s"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vanderheijden86/b9s/releases/download/v1.3.0/b9s_1.3.0_darwin_arm64.tar.gz"
      sha256 "99815b9400fd4e2eff7d27a17088b3046eb618ef57950324d818bdf1ff5fda94"

      define_method(:install) do
        bin.install "b9s"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vanderheijden86/b9s/releases/download/v1.3.0/b9s_1.3.0_linux_amd64.tar.gz"
      sha256 "e11902e5ef116ccc16279b5761a2dc3ccec1fe8be7bb4ce75f30804b2c1da0b0"
      define_method(:install) do
        bin.install "b9s"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vanderheijden86/b9s/releases/download/v1.3.0/b9s_1.3.0_linux_arm64.tar.gz"
      sha256 "bf2ff449c34d3e4e1282b0aa80071739e974c32c8ecd479976cfda746d8e88b2"
      define_method(:install) do
        bin.install "b9s"
      end
    end
  end

  test do
    system "#{bin}/b9s", "--version"
  end
end
