# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class B9s < Formula
  desc "Fast, focused TUI viewer and editor for beads projects"
  homepage "https://github.com/vanderheijden86/beadwork"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vanderheijden86/b9s/releases/download/v0.4.0/b9s_0.4.0_darwin_amd64.tar.gz"
      sha256 "145575aabfa2e9b6607042e1095b8fad997593cc5911b02e325b3c56ff3b5b5f"

      define_method(:install) do
        bin.install "b9s"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vanderheijden86/b9s/releases/download/v0.4.0/b9s_0.4.0_darwin_arm64.tar.gz"
      sha256 "cad3d22b05364a48068796fb7598a7f3307a72be5e7db00dc4b79e4c97b91a41"

      define_method(:install) do
        bin.install "b9s"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vanderheijden86/b9s/releases/download/v0.4.0/b9s_0.4.0_linux_amd64.tar.gz"
      sha256 "323484a6360019336abf5f28b9ad8549e965c3ab4693488304cfcda820d2a69e"
      define_method(:install) do
        bin.install "b9s"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vanderheijden86/b9s/releases/download/v0.4.0/b9s_0.4.0_linux_arm64.tar.gz"
      sha256 "58f005f0ef9562bbd7f173605b12d3cc290bdb4b39d82e0b4e5be7c1cf4440e4"
      define_method(:install) do
        bin.install "b9s"
      end
    end
  end

  test do
    system "#{bin}/b9s", "--version"
  end
end
