# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bw < Formula
  desc "Graph-aware task management TUI for beads projects"
  homepage "https://github.com/vanderheijden86/beadwork"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vanderheijden86/beadwork/releases/download/v0.1.0/bw_0.1.0_darwin_amd64.tar.gz"
      sha256 "d990c7fa169b1f03c126316e1046f44c563f9e6b66dde5f392bfc28496f19939"

      def install
        bin.install "bw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vanderheijden86/beadwork/releases/download/v0.1.0/bw_0.1.0_darwin_arm64.tar.gz"
      sha256 "2a1d55bdc8b3621c8ded34d43e36b142ee365f98d5b1ae3cc4438627af8238c9"

      def install
        bin.install "bw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vanderheijden86/beadwork/releases/download/v0.1.0/bw_0.1.0_linux_amd64.tar.gz"
      sha256 "7c00fd995a9baf4b60c7dd5d9a32e76a71fb9a72179d57f9ba6f7f71fb1e4706"
      def install
        bin.install "bw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vanderheijden86/beadwork/releases/download/v0.1.0/bw_0.1.0_linux_arm64.tar.gz"
      sha256 "29ce624c78c7e5a36624c36e3ca8aeb2a64fe0d14e045f4090ba69fb55bfaa2e"
      def install
        bin.install "bw"
      end
    end
  end

  test do
    system "#{bin}/bw", "--version"
  end
end
